Controllers/MenuHeaderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using ClothingPro.BusinessLayer.DTO;
using ClothingPro.BusinessLayer.Interface;
using ClothingPro.BusinessLayer.BusinessService;
using ClothingPro.Models;

namespace ClothingPro.Web.Controllers
{
    public class MenuHeaderController : BaseController
    {
        private readonly IMenuHeaderService _MenuHeaderService;
        private readonly IStockService _StockService;

        public MenuHeaderController(IMenuHeaderService menuHeaderService, IStockService stockService)
        {
            _MenuHeaderService = menuHeaderService;
            _StockService = stockService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var result = _MenuHeaderService.GetAllMenuHeader();
                return View(result);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }


        [HttpGet]
        public IActionResult Create(int mnId)
        {
            MenuHeaderDTO model = new MenuHeaderDTO();

            if (mnId > 0)
            {
                model = _MenuHeaderService.GetMenuHeaderByIdd(mnId);
            }
            else
            {

            }

            return View("Create", model);
        }

        [HttpPost]
        public IActionResult CreatePost(MenuHeaderDTO model)
        {
            try
            {


                if (ModelState.IsValid)
                {

                    int StId = _MenuHeaderService.CreateMenuHeader(model);
                    return Json("success");
                }


                return View("Create", model);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public JsonResult UpdateMenuHeader(MenuHeaderDTO model)
        {
            try
            {
                _MenuHeaderService.UpdateMenuHeader(model);
                return Json("success");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Delete(int mnId)
        {
            try
            {
                var data = _MenuHeaderService.DeleteMenuHeader(mnId);
                //return this.Ok(data);
                if (data)
                {
                    return Json(new { success = true, message = "Data Deleted Successfully" });
                }
                else // If deletion failed for some reason
                {
                    return Json(new { success = false, message = "Failed to delete the data" });
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult GetStockMenuDetail(int mnId)
        {
            StockMenuView StockMenuViewlists = new StockMenuView();

            if (mnId > 0)
            {
                StockMenuViewlists.StockMenuViewlists = _MenuHeaderService.GetStockMenuDetail(mnId);
            }
            else
            {

            }
            var result = _MenuHeaderService.GetAllMenuHeader();
            StockMenuViewlists.MenuHeaderList = result;
            return View("StockMenuDetail", StockMenuViewlists);
        }


        [HttpGet]
        public IActionResult Search(string search)
        {
            StockMenuView stockmenuviewsearch = new StockMenuView();
            if(search == "All Items")
            {
                ViewBag.SearchHeader = search;
                search = null;
            }
            else
            {
                ViewBag.SearchHeader = search;
            }
            var model = _StockService.GetStockMenuList(search);
            var menuheaderList = _MenuHeaderService.GetAllMenuHeader();

            stockmenuviewsearch.StSearchValue =  ViewBag.SearchHeader;
            stockmenuviewsearch.MenuHeaderList = menuheaderList;


            if (model.Count > 0)
            {
                stockmenuviewsearch.stockmenusearchlist = _StockService.GetStockMenuList(search);
            }
            else
            {
                //return Json("Item Not Found");
                return View("StockMenuDetailSearch", stockmenuviewsearch);
            }

            return View("StockMenuDetailSearch", stockmenuviewsearch);
        }

    }
}

Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using ClothingPro.BusinessLayer.DTO;
using ClothingPro.BusinessLayer.Helper;
using ClothingPro.BusinessLayer.Interface;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using ClothingPro.BusinessLayer.BusinessService;
using ClothingPro.Models;

namespace ClothingPro.Web.Controllers
{
    // [SessionTimeout]
    //[Authorize]
    public class StockController : BaseController
    {
        private readonly IStockService _stockService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IMenuHeaderService _menuHeaderService;
        private readonly IColorImagesService _colorImagesService;

        public StockController(IStockService stockService, IWebHostEnvironment webHostEnvironment, IMenuHeaderService menuHeaderService, IColorImagesService colorImagesService)
        {
            _stockService = stockService;
            _webHostEnvironment = webHostEnvironment;
            _menuHeaderService = menuHeaderService;
            _colorImagesService = colorImagesService;
        }
        public IActionResult Index(int inActive = 0)
        {
            var result = _stockService.GetAllStockBYFilter(inActive);
            ViewBag.InActive = inActive;
            return View(result);
        }

        public IActionResult StockPopularItems()
        {
            var result = _stockService.GetAllKindOfStock();
            return View("StockPopularItems", result.stockPopularList);
        }

        public IActionResult StockPantsItems()
        {
            var result = _stockService.GetAllKindOfStock();
            return View(result.stockPantsList);
        }

        [Route("stock/create-stock")]
        [HttpGet]
        public IActionResult Create(int StId)
        {
            StockDTO model = new StockDTO();

            if (StId > 0)
            {
                model = _stockService.GetStockById(StId);
                model.ColorImagesDTOs = _colorImagesService.GetAllColorImagesListByStockId(StId);

            }
            else
            {

            }
            if (model.StFlagVal == null)
            {
                model.StFlagVal = 0;
            }
            ViewBag.MenuHeaderList = (new MVCHelper()).BindDropdownList("MENUHEADER", false);
            return View("Create", model);
        }


        [HttpGet]
        public IActionResult StockDetail(int StId)
        {
            StockDTO model = new StockDTO();
            var menuheaderList = _menuHeaderService.GetAllMenuHeader();

            if (StId > 0)
            {
                model = _stockService.GetStockById(StId);
                model.MenuHeaderLists = menuheaderList;
                model.ColorImagesDTOs = _colorImagesService.GetAllColorImagesListByStockId(StId);
            }
            else
            {

            }
            //  ViewBag.MenuHeaderList = (new MVCHelper()).BindDropdownList("MENUHEADER", false);
            return View("StockDetail", model);
        }

        //[Route("stock/post-stock")]
        //[HttpPost]
        //public IActionResult CreatePost(StockDTO model)
        //{
        //    try 
        //     {
        //        //if (new MVCHelper().CHECK_DUPLICATE("Stock", "StId", model.StId.ToString(), "StName", model.StName))
        //        //{
        //        //    //ModelState.AddModelError("duplicate", "Stock already exists.");
        //        //    return Json("duplicate", "Stock already exists.");
        //        //}

        //        if (ModelState.IsValid)
        //        {
        //            if (model.StId != 0)
        //            {
        //                var stockdetail = _stockService.GetStockById(model.StId);
        //                model.StImage = stockdetail.StImage;
        //                model.StAddedDate = stockdetail.StAddedDate;
        //            }
        //            else
        //            {
        //                model.StAddedDate = DateTime.Now;
        //            }

        //            int StId = _stockService.CreateStock(model);                 
        //            return Json("success");
        //        }


        //        return View("Create", model);
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(ex.Message);
        //    }
        //}
        [Route("stock/post-stock")]
        [HttpPost]
        public async Task<IActionResult> CreatePost()
        {
            try
            {
                var form = Request.Form;

                // Extract and deserialize model
                var stockInfo = form["model"].ToString();
                var model = JsonConvert.DeserializeObject<StockDTO>(stockInfo);
                var colors = form["StColours"].ToString();
                model.StColour = colors;
                // Extract files
                var stImages = Request.Form.Files;
                var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" };

                if (ModelState.IsValid)
                {
                    var imagePaths = new List<string>();
                    var imagesDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                    if (!Directory.Exists(imagesDirectory))
                    {
                        Directory.CreateDirectory(imagesDirectory);
                    }

                    foreach (var image in stImages)
                    {
                        var fileExtension = Path.GetExtension(image.FileName).ToLowerInvariant();
                        if (!allowedExtensions.Contains(fileExtension))
                        {
                            return BadRequest($"File type not supported: {image.FileName}");
                        }
                        if (image != null && image.Length > 0)
                        {
                            var filePath = Path.Combine(imagesDirectory, Path.GetFileName(image.FileName));
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await image.CopyToAsync(stream);
                            }
                            imagePaths.Add("/images/" + Path.GetFileName(image.FileName));
                        }
                    }

                    model.StImage = string.Join(";", imagePaths);
                    model.StAddedDate = model.StId != 0 ? _stockService.GetStockById(model.StId).StAddedDate : DateTime.Now;
                    if (stImages.Count == 0)
                    {
                        var stockdetail = _stockService.GetStockById(model.StId);
                        if (!string.IsNullOrEmpty(stockdetail.StImage))
                        {
                            model.StImage = stockdetail.StImage;
                        }
                    }

                    _stockService.CreateStock(model);
                    return Json("success");
                }

                return Json("ModelState is not valid.");
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }



        //[Route("stock/delete-stock")]
        [HttpPost]
        public IActionResult Delete(int StId)
        {
            try
            {
                var data = _stockService.DeleteStock(StId);
                //return this.Ok(data);
                if (data)
                {
                    return Json(new { success = true, message = "Data Deleted Successfully" });
                }
                else // If deletion failed for some reason
                {
                    return Json(new { success = false, message = "Failed to delete the data" });
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult UpdateFlag(int stockId, int FlagVal)
        {
            try
            {
                if (stockId != 0)
                {
                    var data = _stockService.GetStockById(stockId);
                    data.StFlagVal = FlagVal;
                    var stockid = _stockService.CreateStock(data);
                    //return this.Ok(data);
                    if (stockid != 0)
                    {
                        if (FlagVal == 0)
                        {
                            return Json(new { success = true, message = "Data Updated Successfully to Normal Color " });
                        }
                        else if (FlagVal == 1)
                        {
                            return Json(new { success = true, message = "Data Updated Successfully To ColorList " });
                        }
                    }
                    else // If deletion failed for some reason
                    {
                        return Json(new { success = false, message = "Failed to Update the data" });

                    }
                }
                return Json(new { success = false, message = "Stock Not Selected" });

            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        //[HttpGet]
        //public JsonResult Search(string search)
        //{
        //    var model = _stockService.GetStockMenuList(search);

        //    return Json(new { model = JsonConvert.SerializeObject(model) });
        //} 


        [HttpGet]
        public JsonResult StockJsonReturn(int StId)
        {
            var model = _stockService.GetStockById(StId);

            return Json(new { model = JsonConvert.SerializeObject(model) });
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClothingPro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClothingPro.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css" rel="stylesheet" />

</head>

<style>

    #dv-quick-search {
        position: absolute;
        top: 100%;
        left: 0;
        right: 0;
        z-index: 1000;
        background-color: white;
        border: 1px solid #ddd;
        border-radius: 0 0 4px 4px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        max-height: 300px;
        overflow-y: auto;
    }

    #tbl-quick-search {
        width: 100%;
        margin-bottom: 0;
    }

        #tbl-quick-search td {
            padding: 8px 12px;
        }

    #closeicon {
        display: block;
        padding: 8px;
        text-align: right;
        cursor: pointer;
    }

    .float-whatsapp {
        position: fixed;
        width: 65px;
        height: 65px;
        bottom: 40px;
        right: 40px;
        background-color: #25d366;
        color: #FFF;
        border-radius: 50px;
        text-align: center;
        font-size: 30px;
        box-shadow: 2px 2px 3px #999;
        z-index: 100;
        display: flex;
        align-items: center;
        justify-content: center;
        text-decoration: none;
        transition: all 0.3s ease;
    }

        .float-whatsapp:hover {
            background-color: #128C7E;
            color: #FFF;
        }

    .my-float {
        margin-top: 16px;
    }
</style>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary mb-3">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Toggle button -->
                <button data-mdb-collapse-init
                        class="navbar-toggler"
                        type="button"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand mt-2 mt-lg-0 fw-bold" asp-controller="Home" asp-action="Index">
                        SHOPPING PRO
                    </a>
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" onclick="DisplaySearchItemsList('All Items')">All Items</a>
                        </li>


                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Stock" asp-action="Index">Stock List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="MenuHeader" asp-action="Index">Menu List</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        }

                    </ul>
                    <!-- Left links -->
                </div>
                <!-- Collapsible wrapper -->

                <div class="input-group" style="max-width:500px; margin-right:25px;">
                    @*  <div class="form-outline" data-mdb-input-init>
                    <input id="search-input" type="search" id="form1" class="form-control" />
                    <label class="form-label" for="form1">Search</label>
                    </div> *@
                    <input id="search-input-value" type="search" id="form1" class="form-control"  />

                    <button id="search-button" type="button" class="btn btn-primary" onclick="DisplaySearchItemsList()">
                        <i class="fas fa-search"></i>
                    </button>
                </div>

                <!-- Right elements -->
                <!-- Right elements -->
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
    </header>
    <div id="dv-quick-search" class="dvsearch" style="display:none;">
        <div id="closeicon" class="text-end">
            <button type="button" class="btn-close" aria-label="Close" onclick="$('#dv-quick-search').hide();"></button>
        </div>
        <table class="table table-hover table-striped table-sm" id="tbl-quick-search">
            <tbody></tbody>
        </table>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-body-tertiary text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <!-- Left -->
            @* <div class="me-5 d-none d-lg-block">
                <span>Get connected with us on social networks:</span>
            </div> *@
            <!-- Left -->
            <!-- Right -->
            <div>
               @*  <a href="" class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a> *@
                <!-- https://wa.me/1234567890 put this in href and replace 1234567890 with actual phone number -->
                <a href="https://wa.me/+9779856625378" class="float-whatsapp" target="_blank">
                    <i class="fa-brands fa-whatsapp fa-lg text-white"></i>
                </a>

               @*  <a href="" class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a> *@
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->
        <!-- Section: Links  -->
       @*  <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Shopping Pro
                        </h6>
                        <p>
                            Here you can use rows and columns to organize your footer content. Lorem ipsum
                            dolor sit amet, consectetur adipisicing elit.
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Men</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Woman</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Kids</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Winter</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Pricing</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Settings</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Orders</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Help</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p><i class="fas fa-home me-3"></i> Kathmandu</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            info@example.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> +977 899898989</p>

                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section> *@
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2024 Copyright:
           @*  <a class="text-reset fw-bold" href="#">shoppingpro.com</a> *@
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/search.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>